#![forbid(unsafe_code)]
use std::collections::BTreeMap;use std::io::{self,Cursor,Read,Write};
use everythingx_protocol::{AdapterError,AdapterErrorKind,AdapterHandshake,CapabilityDescriptor,CapsuleIdentity,InvocationRequest,InvocationResult,InvocationStatus,LossLevel,Measurements,ProtocolVersion,Provenance,StaticAdapter};
use raw_pcm_endian_signedness_normalize::{Error as CapsuleError,Options};
pub const ADAPTER_ID:&str="adapter:raw-pcm-endian-signedness-normalize-static";pub const CAPABILITY_ID:&str="capability:raw-pcm-endian-signedness-normalize/frame-exact/native-portable";pub struct GeneratedRawPcmAdapter;
fn defaults()->BTreeMap<String,String>{BTreeMap::from([("bits_per_sample".into(),"16".into()),("buffer_size".into(),"65536".into()),("channel_map".into(),"0".into()),("channels".into(),"1".into()),("frame_count".into(),"all".into()),("input_encoding".into(),"signed".into()),("input_endianness".into(),"little".into()),("max_channels".into(),"256".into()),("output_encoding".into(),"signed".into()),("output_endianness".into(),"big".into()),("start_frame".into(),"0".into())])}
fn descriptor()->CapabilityDescriptor{CapabilityDescriptor{capability_id:CAPABILITY_ID.into(),source_formats:vec!["exfmt:audio:raw-pcm".into()],target_formats:vec!["exfmt:audio:raw-pcm".into()],strategy:"frame-exact".into(),backend:"native-portable".into(),default_options:defaults(),defaults_are_runnable:true,streaming:false,seek_required:false}}
struct Limited<'a>{inner:&'a mut dyn Write,remaining:u64,exceeded:bool}impl Write for Limited<'_>{fn write(&mut self,b:&[u8])->io::Result<usize>{if b.len()as u64>self.remaining{self.exceeded=true;return Err(io::Error::other("output budget exceeded"));}let n=self.inner.write(b)?;self.remaining-=n as u64;Ok(n)}fn flush(&mut self)->io::Result<()>{self.inner.flush()}}
impl StaticAdapter for GeneratedRawPcmAdapter{fn handshake(&self)->AdapterHandshake{AdapterHandshake{protocol:ProtocolVersion::CURRENT,adapter_id:ADAPTER_ID.into(),adapter_version:"0.1.0".into(),capsule:CapsuleIdentity{id:"capsule:raw-pcm-endian-signedness-normalize".into(),version:"0.1.0".into(),content_hash:None},capabilities:vec![descriptor()]}}fn invoke(&self,request:&InvocationRequest,input:&mut dyn Read,output:&mut dyn Write)->Result<InvocationResult,AdapterError>{if request.capability_id!=CAPABILITY_ID{return Err(AdapterError::new(AdapterErrorKind::UnsupportedCapability,"unsupported capability"));}if request.options!=defaults(){return Err(AdapterError::new(AdapterErrorKind::InvalidOptions,"version 0.1 static Adapter accepts its declared defaults"));}let limit=request.resource_budget.max_memory_bytes.saturating_sub(131_072);let mut bytes=Vec::new();input.take(limit.saturating_add(1)).read_to_end(&mut bytes).map_err(|e|AdapterError::new(AdapterErrorKind::Io,e.to_string()))?;if bytes.len()as u64>limit{return Err(AdapterError::new(AdapterErrorKind::ResourceLimit,"input exceeds memory budget"));}let memory=bytes.len()as u64;let mut cursor=Cursor::new(bytes);let mut limited=Limited{inner:output,remaining:request.resource_budget.max_output_bytes,exceeded:false};let report=raw_pcm_endian_signedness_normalize::convert(&mut cursor,&mut limited,&Options::default()).map_err(|e|match e{CapsuleError::Io(io)if limited.exceeded=>AdapterError::new(AdapterErrorKind::ResourceLimit,io.to_string()),CapsuleError::Io(io)=>AdapterError::new(AdapterErrorKind::Io,io.to_string()),other=>AdapterError::new(AdapterErrorKind::InvalidInput,other.to_string())})?;let handshake=self.handshake();Ok(InvocationResult{status:InvocationStatus::Succeeded,effects:BTreeMap::from([("format".into(),"exfmt:audio:raw-pcm".into())]),losses:BTreeMap::from([("payload".into(),LossLevel::None),("temporal".into(),LossLevel::Normalized),("structure".into(),LossLevel::Normalized),("metadata".into(),LossLevel::None)]),measurements:Measurements{input_bytes:Some(report.input_bytes),output_bytes:Some(report.output_bytes),peak_memory_bytes:Some(memory+report.peak_working_memory_bytes),..Measurements::default()},capsule_report:BTreeMap::from([("input_frames".into(),report.input_frames.to_string()),("output_frames".into(),report.output_frames.to_string()),("input_channels".into(),report.input_channels.to_string()),("output_channels".into(),report.output_channels.to_string()),("bits_per_sample".into(),report.bits_per_sample.to_string())]),warnings:report.warnings,provenance:Provenance{capsule:handshake.capsule,adapter_id:handshake.adapter_id,adapter_version:handshake.adapter_version,capability_id:CAPABILITY_ID.into(),strategy:"frame-exact".into(),backend:"native-portable".into(),effective_options:defaults()}})}}
#[cfg(test)]mod tests{use super::*;use everythingx_kernel::Kernel;#[test]fn kernel_invokes_runnable_defaults(){let mut kernel=Kernel::default();kernel.register(Box::new(GeneratedRawPcmAdapter)).unwrap();let fixture=raw_pcm_endian_signedness_normalize::conformance_fixture();let mut input=&fixture[..];let mut output=Vec::new();let result=kernel.invoke_defaults(ADAPTER_ID,CAPABILITY_ID,&mut input,&mut output).unwrap();assert_eq!(result.status,InvocationStatus::Succeeded);assert!(!output.is_empty());}}
