#!/usr/bin/env python3
"""Generate the dependency and registration list for the all-Capsule benchmark."""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HARNESS = ROOT / "benchmarks" / "capability-bench"
CARGO = HARNESS / "Cargo.toml"
REGISTRY = HARNESS / "src" / "generated_adapters.rs"


def discover() -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    manifests = sorted((ROOT / "capsules").rglob("everythingx/adapter/Cargo.toml"))
    for manifest in manifests:
        if "_template" in manifest.parts:
            continue
        source = manifest.parent / "src" / "lib.rs"
        cargo_text = manifest.read_text(encoding="utf-8")
        source_text = source.read_text(encoding="utf-8")
        package = re.search(r'^name\s*=\s*"([^"]+)"', cargo_text, re.MULTILINE)
        adapter_type = re.search(r"pub struct\s+([A-Za-z][A-Za-z0-9_]*)", source_text)
        if package is None or adapter_type is None:
            raise ValueError(f"cannot discover package/type from {manifest}")
        relative = os.path.relpath(manifest.parent, HARNESS)
        rows.append((package.group(1), relative, adapter_type.group(1)))
    return rows


def cargo_text(rows: list[tuple[str, str, str]]) -> str:
    lines = [
        "[package]",
        'name = "everythingx-capability-bench"',
        'version = "0.1.0"',
        'edition = "2024"',
        "publish = false",
        "",
        "[dependencies]",
        'everythingx-kernel = { path = "../../kernel/ex-kernel" }',
        'everythingx-protocol = { path = "../../kernel/ex-protocol" }',
    ]
    for index, (package, path, _) in enumerate(rows):
        lines.append(f'adapter_{index:03} = {{ package = "{package}", path = "{path}" }}')
    return "\n".join(lines) + "\n"


def registry_text(rows: list[tuple[str, str, str]]) -> str:
    lines = [
        "// Generated by tools/build_performance_harness.py; do not edit.",
        "use everythingx_kernel::Kernel;",
        "use everythingx_protocol::{AdapterHandshake, StaticAdapter};",
        "",
        f"pub const ADAPTER_COUNT: usize = {len(rows)};",
        "",
        "pub fn register_all(kernel: &mut Kernel) -> Vec<AdapterHandshake> {",
        "    let mut handshakes = Vec::new();",
    ]
    for index, (_, _, adapter_type) in enumerate(rows):
        lines.extend([
            f"    let adapter = adapter_{index:03}::{adapter_type};",
            "    handshakes.push(adapter.handshake());",
            "    kernel.register(Box::new(adapter)).expect(\"generated Adapter registry must be unique\");",
        ])
    lines.extend(["    handshakes", "}", ""])
    return "\n".join(lines)


def materialize(check: bool) -> int:
    rows = discover()
    expected = {CARGO: cargo_text(rows), REGISTRY: registry_text(rows)}
    stale = []
    for path, content in expected.items():
        if check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("performance harness is stale: " + ", ".join(map(str, stale)))
        return 1
    if check:
        print(f"performance harness is current ({len(rows)} production Capsule Adapters)")
    else:
        print(f"generated performance harness for {len(rows)} production Capsule Adapters")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    return materialize(parser.parse_args().check)


if __name__ == "__main__":
    raise SystemExit(main())
