#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::io::{self, Cursor, Read, Write};
use everythingx_protocol::{AdapterError, AdapterErrorKind, AdapterHandshake, CapabilityDescriptor, CapsuleIdentity, InvocationRequest, InvocationResult, InvocationStatus, LossLevel, Measurements, ProtocolVersion, Provenance, StaticAdapter};
use bw64_pcm_to_wave64_pcm::{Error as CapsuleError, Options};

pub const ADAPTER_ID:&str="adapter:bw64-pcm-to-wave64-pcm-static";
pub const CAPABILITY_ID:&str="capability:bw64-pcm-to-wave64-pcm/pcm-exact/native-portable";
pub struct GeneratedPcmAdapter;
fn defaults()->BTreeMap<String,String>{BTreeMap::from([("buffer_size".into(),"65536".into()),("max_channels".into(),"256".into()),("strict_header_consistency".into(),"true".into())])}
fn descriptor()->CapabilityDescriptor{CapabilityDescriptor{capability_id:CAPABILITY_ID.into(),source_formats:vec!["exfmt:audio:bw64-pcm".into()],target_formats:vec!["exfmt:audio:wave64-pcm".into()],strategy:"pcm-exact".into(),backend:"native-portable".into(),default_options:defaults(),defaults_are_runnable:true,streaming:false,seek_required:false}}
struct Limited<'a>{inner:&'a mut dyn Write,remaining:u64,exceeded:bool}
impl Write for Limited<'_>{fn write(&mut self,b:&[u8])->io::Result<usize>{if b.len()as u64>self.remaining{self.exceeded=true;return Err(io::Error::other("output budget exceeded"));}let n=self.inner.write(b)?;self.remaining-=n as u64;Ok(n)}fn flush(&mut self)->io::Result<()>{self.inner.flush()}}
impl StaticAdapter for GeneratedPcmAdapter{
fn handshake(&self)->AdapterHandshake{AdapterHandshake{protocol:ProtocolVersion::CURRENT,adapter_id:ADAPTER_ID.into(),adapter_version:"0.1.0".into(),capsule:CapsuleIdentity{id:"capsule:bw64-pcm-to-wave64-pcm".into(),version:"0.1.0".into(),content_hash:None},capabilities:vec![descriptor()]}}
fn invoke(&self,request:&InvocationRequest,input:&mut dyn Read,output:&mut dyn Write)->Result<InvocationResult,AdapterError>{
if request.capability_id!=CAPABILITY_ID{return Err(AdapterError::new(AdapterErrorKind::UnsupportedCapability,"unsupported capability"));}if request.options!=defaults(){return Err(AdapterError::new(AdapterErrorKind::InvalidOptions,"version 0.1 static Adapter accepts its declared defaults"));}
let reserve=65_536u64;let limit=request.resource_budget.max_memory_bytes.saturating_sub(reserve);let mut bytes=Vec::new();input.take(limit.saturating_add(1)).read_to_end(&mut bytes).map_err(|e|AdapterError::new(AdapterErrorKind::Io,e.to_string()))?;if bytes.len()as u64>limit{return Err(AdapterError::new(AdapterErrorKind::ResourceLimit,"input exceeds memory budget"));}let input_memory=bytes.len()as u64;let mut cursor=Cursor::new(bytes);let mut limited=Limited{inner:output,remaining:request.resource_budget.max_output_bytes,exceeded:false};
let report=bw64_pcm_to_wave64_pcm::convert(&mut cursor,&mut limited,&Options::default()).map_err(|error|match error{CapsuleError::Io(e)if limited.exceeded=>AdapterError::new(AdapterErrorKind::ResourceLimit,e.to_string()),CapsuleError::Io(e)=>AdapterError::new(AdapterErrorKind::Io,e.to_string()),other=>AdapterError::new(AdapterErrorKind::InvalidInput,other.to_string())})?;let handshake=self.handshake();
Ok(InvocationResult{status:InvocationStatus::Succeeded,effects:BTreeMap::from([("format".into(),"exfmt:audio:wave64-pcm".into())]),losses:BTreeMap::from([("payload".into(),LossLevel::None),("temporal".into(),LossLevel::None),("structure".into(),LossLevel::Normalized),("metadata".into(),LossLevel::Unbounded)]),measurements:Measurements{input_bytes:Some(report.input_bytes),output_bytes:Some(report.output_bytes),peak_memory_bytes:Some(input_memory+report.peak_working_memory_bytes),..Measurements::default()},capsule_report:BTreeMap::from([("channels".into(),report.channels.to_string()),("sample_rate".into(),report.sample_rate.to_string()),("container_bits_per_sample".into(),report.container_bits_per_sample.to_string()),("valid_bits_per_sample".into(),report.valid_bits_per_sample.to_string()),("sample_frames".into(),report.sample_frames.to_string())]),warnings:report.warnings,provenance:Provenance{capsule:handshake.capsule,adapter_id:handshake.adapter_id,adapter_version:handshake.adapter_version,capability_id:CAPABILITY_ID.into(),strategy:"pcm-exact".into(),backend:"native-portable".into(),effective_options:defaults()}})
}}
#[cfg(test)]mod tests{use super::*;use everythingx_kernel::Kernel;#[test]fn kernel_invokes_runnable_defaults(){let mut kernel=Kernel::default();kernel.register(Box::new(GeneratedPcmAdapter)).unwrap();let fixture=bw64_pcm_to_wave64_pcm::conformance_fixture();let mut input=&fixture[..];let mut output=Vec::new();let result=kernel.invoke_defaults(ADAPTER_ID,CAPABILITY_ID,&mut input,&mut output).unwrap();assert_eq!(result.status,InvocationStatus::Succeeded);assert!(!output.is_empty());}}
